#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the diagonalDifference function below.
def diagonalDifference(arr):
    r=c=0
    n=len(arr)
    d=n-1
    h=[n]
    sum1=sum2=0
    for i in range(n):
        narr =arr[i][i]
        sarr =arr[i][d]
        i=i+1
        d=d-1
        sum1=sum1+narr
        sum2=sum2+sarr
    result=sum1-sum2
    result=abs(result)
    return result
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
